### ISSUE TITLE
`per_page` option stopped working after version 0.0.2

### ISSUE THREAD

**Issue by michaelcd** [carrot/rooftop-node#6]
It appears as though adding a per_page option  stopped working in version 1.0.0, so that queries will still return the default number of posts (10). This might affect adding other options/params to a query as well.

Using the following test with my project:

``` javascript
api.awards.get({ per_page: 20 })
  .then((result) => console.log(result.length))
```

Version 0.0.2 logs 16.
Version 1.0.0 logs 10.

**Comment by michaelcd** [comment]
I'd assign myself but I don't have permission. 😄  In the meantime I'll see if I can pinpoint the issue.

**Comment by kylemac** [comment]
you have access now

**Comment by edtjones** [comment]
Is this an API issue folks? I'm sure we haven't changed that on our side but wanted to be certain you're referring to an issue with the JS lib :-)

## 

Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by michaelcd** [comment]
Ed, it appears to be an issue with the library, not the API. 😄

**Comment by edtjones** [comment]
That's ok then :)

**Comment by michaelcd** [comment]
The issue is related to update of rest to `2.0.0`.

"Moved path token param replacement from the clients into the rest/interceptor/params interceptor, which is also deprecated. **The behavior will no longer be applied automatically in the client.** Using the rest/interceptor/template interceptor is far more powerful and preferred."

So params aren't being handled automatically anymore, so the `per_page` option is never making it into the request.

**Comment by kylemac** [comment]
you probably know this already from your research, but sounds to me like you should be able to add + include the `template` interceptor and wrap the request in it. 

examples of other interceptors:
https://github.com/carrot/rooftop-node/blob/master/lib/index.js#L37-L40

**Comment by michaelcd** [comment]
Yup working on that now. Thanks 😄
